### ISSUE TITLE
Compatibility with Kirby blocks

### ISSUE THREAD

**Issue by MaluNoPeleke** [gearsdigital/enhanced-toolbar-link-dialog#59]
Can you please add support for Kirby blocks links?
I have installed your latest plugin on my Kirby 3.6 environment and cannot see any difference for blocks links.

**Comment by gearsdigital** [comment]
Howdy @MaluNoPeleke 🤠 Thank you very much for trying out my plugin! Could you please provide some more details? I'm not sure if I fully understand your use case.

It works as expected If you setup a custom block which uses a textarea.

```yml
fields:
    blocks:
      type: blocks
      fieldsets:
        - text
        text:
          name: Text
          icon: bolt
          fields:
            link:
              type: textarea
```

<img width="1276" alt="Bildschirmfoto 2021-12-01 um 23 19 46" src="https://user-images.githubusercontent.com/965069/144323385-d582362f-70da-4c95-93a8-0d1bf6cab01b.png">

**Comment by MaluNoPeleke** [comment]
I am still new to Kirby and currently migrating my website from Ghost CMS.
This is my blueprint that I have tested:

```
    columns:
      main:
        width: 2/3
        fields:
          author:
            type: users
            label: Autor
            width: 1/2
            translate: false
          modified:
            type: info 
            label: Letzte Änderung
            theme: none
            text: "{{ page.modified('%d.%m.%Y %H:%M') }}"
            width: 1/2
            align: right
          intro: 
            type: text
            label: Intro
          text: 
            type: blocks
            label: Artikel
            autofocus: true
            default:
              - type: text
```

This is how it looks like and I expected a replacement of the link feature with your enhanced version:
![image](https://user-images.githubusercontent.com/1446541/144497386-f0b32d39-f97c-4c75-9898-70082119181d.png)
